# -*- coding: utf-8 -*-
"""helloworld!

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UOTHIlfq_1xpzdiiUZQGJjn3Gc5f4jCH
"""

print("Hello world!")